name: Basic GitHub actions run
on: push
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 10.15.3
        uses: actions/setup-node@v1
        with:
          version: 10.15.3
      - name: Build
        run: |
          npm install
          npm run build --if-present
